[alacritty]
src.git = "https://codeberg.org/evergarden/alacritty.git"
fetch.git = "https://codeberg.org/evergarden/alacritty.git"
[base16]
src.git = "https://codeberg.org/evergarden/base16.git"
fetch.git = "https://codeberg.org/evergarden/base16.git"
[bat]
src.git = "https://codeberg.org/evergarden/bat.git"
fetch.git = "https://codeberg.org/evergarden/bat.git"
[dunst]
src.git = "https://codeberg.org/evergarden/dunst.git"
fetch.git = "https://codeberg.org/evergarden/dunst.git"
[ghostty]
src.git = "https://codeberg.org/evergarden/ghostty.git"
fetch.git = "https://codeberg.org/evergarden/ghostty.git"
[foot]
src.git = "https://codeberg.org/evergarden/foot.git"
fetch.git = "https://codeberg.org/evergarden/foot.git"
[iterm]
src.git = "https://codeberg.org/evergarden/iterm.git"
fetch.git = "https://codeberg.org/evergarden/iterm.git"
[kitty]
src.git = "https://codeberg.org/evergarden/kitty.git"
fetch.git = "https://codeberg.org/evergarden/kitty.git"
[lazygit]
src.git = "https://codeberg.org/evergarden/lazygit.git"
fetch.git = "https://codeberg.org/evergarden/lazygit.git"
[scss]
src.git = "https://codeberg.org/evergarden/scss.git"
fetch.git = "https://codeberg.org/evergarden/scss.git"
[spicetify]
src.git = "https://codeberg.org/evergarden/spicetify.git"
fetch.git = "https://codeberg.org/evergarden/spicetify.git"
[tmux]
src.git = "https://codeberg.org/evergarden/tmux.git"
fetch.git = "https://codeberg.org/evergarden/tmux.git"
[zathura]
src.git = "https://codeberg.org/evergarden/zathura.git"
fetch.git = "https://codeberg.org/evergarden/zathura.git"
[helix]
src.git = "https://codeberg.org/evergarden/helix.git"
fetch.git = "https://codeberg.org/evergarden/helix.git"
